name: Composite

on:
  push: 

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: retrieve
        id: retrieve
        uses:  ./.github/actions/sayhello

      - name: Show said
        run: |
          echo "said: ${{ steps.retrieve.outputs.said}}"
